
<section>
  <article>
    <h3>Thés</h3>
    <div class="flex space-around basline menu-items">
      <div >
        <h4>Blanc 4,50€</h4>
        <p>Satsuma Yusu (4 agrumes)</p>
        <p>Passion Fleurs (abricot, fruit de la passion, rose)</p>

        <h4>Vert 3,70€</h4>
        <p>Sencha Calida (feuilles de Sencha, fruits rouges)</p>
        <p>Riads (cannelle, cardamone, pigment, citron, pamplemousse)</p>
        <p>Bali (letchi, rose, jasmin, pamplemousse)</p>
        <p>Genmicha (feuilles de Sancha, riz et mais soufflé) 3,90€</p>
        <p>Sencha Fukuyu (feuilles de Sancha bio) 3,90€</p>
      </div>

      <div>
        <h4>Noir 3,70€</h4>
        <p>Earl Grey Fleurs (supérieure)</p>
        <p>Ceylan</p>
        <p>Ronde d’automne (noisette, vanille)</p>

        <h4>Rouge 3,70€</h4>
        <p>Rooibos fruits fleurs (fraise, vanille, bluet, pamplemousse, pétales de tournesol)</p>
        <p>Rooibos caramel (caramel)</p>
        <p>Rooibos tropical (orange, fraise, framboise, coco et pétales de bluets)</p>
      </div>
    </div>
    <div class="menu-items">
      <h4>Infusions 3,70€</h4>
      <p>Relaxation (Rooibos, feuilles de mélisse, fleurs de mûrier,  arôme orange et caramel)</p>
      <p>Bissap (fleurs d’hibiscus)</p>
      <p>Belle endormie (tilleul, menthe, verveine)</p>
    </div>
  </article>
  <article>
    <div class="flex space-around basline menu-items">
      <div>
        <h3>Cafés</h3>

        <p>Expresso 1,80€</p>
        <p>Ristretto 1,80€</p>
        <p>Allongé 2,00€</p>
        <p>Crème 2,20€</p>
        <p>Moka 4,00€ (Viennois 4,50€)</p>
        <p>Cappuccino 4,00€ (Viennois 4,50€)</p>
      </div>
      <div>
        <h3>Chocolats</h3>
        <p>Grand 3,50€ (Viennois 4,00€)</p>
        <p>Chamallow 4,00€ (Viennois 5,00€)</p>
      </div>
    </div>
  </article>

  <article>
    <div class="flex space-around basline menu-items">
      <div>
        <h3>Les softs</h3>
        <p>Coca-cola 33cl 3,00€</p>
        <p>Coca-cola zero 33cl 3,10€</p>
        <p>Ice tea 33cl 3,00€</p>
        <p>Orangina 33cl 3,00€</p>
        <p>Diabolo 33cl 3,00€</p>
        <p>Perrier 33cl 3,00€</p>
        <p>Perrier citron 33cl 3,00€</p>
        <p>limonade 33cl 2,90€</p>
        <p>Jus de fruits (orange, ananas, pomme...) 25cl 3,00€</p>
        <p>Evian 50cl 3,20€</p>
        <p>Badoit 50cl 3,20€</p>
        <p>Lait fraise 25cl 3,00€</p>
        <p>Sirop (banane, fraise, litchi, banane-kiwi ...) 25cl 2,20€</p>
      </div>
      <div>
        <h3>Alcool</h3>
        <p>(pendent les repas uniquement)</p>
        <p>Vin 4,00€</p>
        <p>Cidre 4,00€</p>
        <p>Bière 4,00€</p>
      </div>
    </div>
  </article>
</section>
