<section>
  <article>
    <h3>Nos chats</h3>
    <img src="img/ourmia.jpg" alt="Photo d'Ourmia">
    <p>Tous nos chats font l'objet d'un suivi vétérinaire exigeant et régulier. Ils sont vaccinés (+rappel), stérilisés, identifiés (pucés) et soignés contre les parasites.</p>
    <p>Nos locataires sont triés sur le volet par l'association Ker Kaz'h sur des critères d'équilibre, de santé et de sociabilité. Ils viennent donc de familles d'accueil dans lesquelles, souvent, ils ont pu être au contact d'enfants comme de congénères. Ces boules de poils ont toutes une histoire difficiles mais se réparent tranquillement au Chat Puccino en attendant leur nouvelle famille : peut être vous?</p>
  </article>

  <article>
    <h3>Ils attendent leurs famille</h3>
    <div class="flex space-between direction-row">
      <div>
        <img src="img/cats/livio.jpg" alt="Photo de Livio chat noir">
        <figcaption>Livio</figcaption>
      </div>
      <div>
        <img src="img/cats/omael.jpg" alt="Photo de Omael chat gris et blanc">
        <figcaption>OMaël</figcaption>
      </div>
      <div>
        <img src="img/cats/lax.jpg" alt="Photo de Lax chat blanc tigré">
        <figcaption>Lax</figcaption>
      </div>
    </div>
  </article>
</section>
