
        <section>
          <h2>Ce que nous sommes</h2>
          <article>
            <h3>Un Concept Authentique</h3>
            <img src="img/presentation.jpg" alt="photo vitrine presentation de café">
            <p>Nous sommes beaucoup plus qu'un simple bar où se baladent nonchalamment quelques chats.</p>
            <p>Ici, au coeur d'une culture venue du Japon et très librement modernisée, tout est avant tout fait pour le bien être du chat avec le client et du client avec nos adorables ronron-thérapeutes.</p>
          </article>

          <article>
            <h3>La ronronthérapie ?</h3>
            <img src="img/vitrine.jpg" alt="Photo des ronrothérapeuts">
            <p>C'est cette magie autour de laquelle s'est construite l'idée de Sophie (la gérante) et par laquelle, en entrant au Chat Puccino, vous pourrez laisser tout ce qui vous ennuie dehors. Au bar à chat, moelleusement installé(e) sur un gros fauteuil en cuir, un chat étendu de toute sa longueur sur vos genoux et un autre assis sur le dossier du canapé (en train de voler un câlin à votre joue), vous êtes très loin mais aussi décontracté(e) qu'à la maison. Bienvenue chez vous !</p>
          </article>

          <article>

            <h3>Nos chats</h3>
            <img src="img/ourmia.jpg" alt="Photo d'Ourmia">
            <p>Tous nos chats font l'objet d'un suivi vétérinaire exigeant et régulier. Ils sont vaccinés (+rappel), stérilisés, identifiés (pucés) et soignés contre les parasites.</p>
            <p>Nos locataires sont triés sur le volet par l'association Ker Kaz'h sur des critères d'équilibre, de santé et de sociabilité. Ils viennent donc de familles d'accueil dans lesquelles, souvent, ils ont pu être au contact d'enfants comme de congénères. Ces boules de poils ont toutes une histoire difficiles mais se réparent tranquillement au Chat Puccino en attendant leur nouvelle famille : peut être vous?</p>
          </article>
        </section>
