<section>
  <article>
    <h3>Comment nous trouver?</h3>
    <a href="https://goo.gl/maps/Pe3FfBwpPnVt2kqq8" rel="nofollow noindex"><img src="img/carte.jpg" alt="Plan pour se rendre à chat puccino" id="plan"></a>
    <ul>
      <li>Adresse : 1, rue des Francs Bourgeois à Rennes.</li>
      <li>Proche de la place Saint-Germain et du Musée des Beaux-Arts.</li>
      <li>Métro ligne A : République</li>
      <li>Métro ligne B : St-Germain</li>
      <li>A 15 min à pied depuis la gare</li>
      <li>Vous pouvez vous garer au Parking Couvert Kleber</li>
    </ul>
  </article>
  <article class="align-center">
    <h3>Heures d'ouverture</h3>
    <p>Du Mardi au Samedi de 12h à 19h</p>
    <p>Fermé les Dimanche, Lundi et jours feriés</p>
    <p>Tuesday – Saturday  7am – 8pm</p>
    <p>Closed Sunday and Monday</p>
  </article>
</section>
