</main>
<footer>
  <h3>Nous contacter</h3>
  <ul>
    <li>E-mail : chatpuccino@gmail.com</li>
    <li><a href="https://www.facebook.com/Le-Chat-Puccino-1666466800286265/" rel="nofollow noindex"><i class="fab fa-facebook-square"></i> Le Chat Puccino sur Facebook</a></li>
    <li><a href="https://www.instagram.com/explore/locations/1666466800286265/le-chat-puccino" rel="nofollow noindex"> <i class="fab fa-instagram"></i>Le Chat Puccino sur Instagram</a></li>
  </ul>
  <a href="http://a.pagnoux.free.fr/" rel="nofollow" id="realisateur">Ce site est réalisé par Anastassiya Pagnoux</a>
</footer>
</div>
</body>
