<!DOCTYPE html>
<html lang="fr" >
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-141137047-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-141137047-2');
</script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Venez passer un moment convivial fait de paresse et de tendresse en compagnie de nos résidents à moustaches et à poils, experts en ronronthérapie. Le tout, dans une ambiance cosy, familiale et détendue." />
    <meta name="robots" content="index, follow" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <title>Le Chat Puccino - Premier Bar à Chat en Bretagne</title>
  </head>

  <body>
    <div id="wrap">
      <header>
        <div class="conteiner flex">
          <a href="index.php?page=presentation"><img src="img/logo-chapuccino.png" alt="Logo - Le Chat Puccino"></a>
          <a href="index.php?page=presentation"><h1>Le Chat Puccino - Bar à Chat, Neko café</h1></a>
        </div>
      </header>
      <nav class="conteiner">
        <ul id="nav" class="flex space-between grow-1 direction-row">
          <?php print_nav($headings); ?>
        </ul>
      </nav>
      <main>
