
        <section>
          <h2>Ce que nous sommes</h2>
          <article>
            <h3>Un Concept Authentique</h3>
            <img src="img/presentation.jpg" alt="photo vitrine presentation de café">
            <p>Nous sommes beaucoup plus qu'un simple bar où se baladent nonchalamment quelques chats.</p>
            <p>Ici, au coeur d'une culture venue du Japon et très librement modernisée, tout est avant tout fait pour le bien être du chat avec le client et du client avec nos adorables ronron-thérapeutes.</p>
          </article>

          <article>
            <h3>La ronronthérapie ?</h3>
            <img src="img/vitrine.jpg" alt="Photo des ronrothérapeuts">
            <p>C'est cette magie autour de laquelle s'est construite l'idée de Sophie (la gérante) et par laquelle, en entrant au Chat Puccino, vous pourrez laisser tout ce qui vous ennuie dehors. Au bar à chat, moelleusement installé(e) sur un gros fauteuil en cuir, un chat étendu de toute sa longueur sur vos genoux et un autre assis sur le dossier du canapé (en train de voler un câlin à votre joue), vous êtes très loin mais aussi décontracté(e) qu'à la maison. Bienvenue chez vous !</p>
          </article>
        </section>
